### ISSUE TITLE
How do I set up a tired menu for my website?

### ISSUE THREAD

**Issue by medewitt** [WFU-TLC/flc_discussion_board#23]
Ideally we want multiple drop downs on the website e.g.
```
|-research
  |-abstract
  |- introduction
  |- methods
  |- etc
```

**Comment by medewitt** [comment]
Dan's awesome example saved as a `_site.yml` file

```
name: "Analyzing TA Comments in R"
output_dir: "docs"
navbar:
  title: "Analyzing TA Comments in R"
  right:
  - text: "Notes"
    icon: fa-sticky-note
    href: notes.html
  - text: "Background"
    icon: fa-history
    href: background.html
  - text: "Lit Review"
    icon: fa-search
    href: litreview.html
    menu: 
    - text: "Overview"
      icon: fa-search
      href: litreview.html
    - text: "Teaching Writing"
      icon: fa-chalkboard
      href: techwriting.html
    - text: "Training Future Faculty"
      icon: fa-chalkboard-teacher
      href: futurefaculty.html
    - text: "Automated Text Analysis"
      icon: fa-chart-bar
      href: aacr.html
    - text: "Intro to Text Classification"
      icon: fa-sort-amount-down
      href: Text_Classifier_Models.html
    - text: "Topic Modeling"
      icon: fa-code-branch
      href: Topic_categorization.html
    - text: "Choosing a Classifier"
      icon: fa-hand-point-up
      href: Choosing_classifier.html
    - text: "Evaluating Outcomes"
      icon: fa-edit
      href: Improving_classifier.html
  - text: "The Build"
    icon: fa-puzzle-piece
    href: build.html
    menu: 
    - text: "Overview"
      icon: fa-puzzle-piece
      href: build.html
    - text: "Comment Extraction"
      icon: fa-cut
      href: docxcommentextraction.html
    - text: "Classification Codebook"
      icon: fa-book
      href: codebook.html
    - text: "About the Dataset"
      icon: fa-sign-in-alt
      href: dataimport.html
    - text: "Initial Exploration"
      icon: fa-eye
      href: initial_exploration.html
    - text: "NB Classifier"
      icon: fa-map-marker-alt
      href: NB_2r2c.html
    - text: "Ensemble Classifier"
      icon: fa-archive
      href: Ensemble_Notes.html
  - text: "Data Exploration"
    icon: fa-question-circle
    href: initial_exploration.html
  - text: "Findings"
    icon: fa-chart-bar
    href: findings.html
  - text: "Next Steps"
    icon: fa-shoe-prints
    href: sitemap.html
output:
  html_document:
    theme: journal
    highlight: textmate
    css: css/style.css
    df_print: paged
    toc: true
    toc_float: yes
    bibliography: library.bib
    biblio-style: apalike
    include:
      after_body: footer.html
```
